server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-clientes
          uri: lb://api-clientes
          predicates:
            - Path=/api/clientes/v1/**
          filters:
            - StripPrefix=3
        - id: api-cuentas
          uri: lb://api-cuentas
          predicates:
            - Path=/api/cuentas/v1/**
          filters:
            - StripPrefix=3
        - id: api-creditos
          uri: lb://api-creditos
          predicates:
            - Path=/api/creditos/v1/**
          filters:
            - StripPrefix=3
        - id: api-cuentas-operaciones
          uri: lb://api-cuentas-operaciones
          predicates:
            - Path=/api/cuentas-operaciones/v1/**
          filters:
            - StripPrefix=3
        - id: api-creditos-pagos
          uri: lb://api-creditos-pagos
          predicates:
            - Path=/api/creditos-pagos/v1/**
          filters:
            - StripPrefix=3
        - id: api-creditos-consumos
          uri: lb://api-creditos-consumos
          predicates:
            - Path=/api/creditos-consumos/v1/**
          filters:
            - StripPrefix=3
        - id: api-movimientos
          uri: lb://api-movimientos
          predicates:
            - Path=/api/movimientos/v1/**
          filters:
            - StripPrefix=3
        - id: api-saldos
          uri: lb://api-saldos
          predicates:
            - Path=/api/saldos/v1/**
          filters:
            - StripPrefix=3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: localhost
